### PR TITLE
del future_poll_fn

### PR DESCRIPTION
**Pull request by theavege**
fixed CI error

### CODE REVIEW

**Comment by theavege** [comment]
[FYI](https://github.com/CM-IV/crypto_rs/pull/2#issuecomment-2403377887)

**Comment by PonasKovas** [comment]
Uhmm why did you link this? Forgot to change accounts?

I'm probably gonna revert your changes now, sorry if you're genuine, but this project is dead either way. I don't want any trouble with GitHub and misusing their actions. This repository should have been archived anyway, and I will probably do it now.

**Comment by PonasKovas** [comment]
@theavege If you have anything to say, please do. I will archive this repository in a few hours for good and the issues will be locked.

**Comment by theavege** [comment]
@PonasKovas I explained my actions there. Sorry to bother you.
Before archiving, could you update the dependency versions?

**Pull request merged**
